-- fix-users-sequence.sql
-- Exit on error in psql: \set ON_ERROR_STOP on
-- 1) Create sequence if missing and start after current max(user_id)
DO $$
DECLARE m bigint;
BEGIN
  SELECT COALESCE(MAX(user_id), 0) + 1 INTO m FROM users;
  IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relkind = 'S' AND relname = 'users_user_id_seq') THEN
    EXECUTE format('CREATE SEQUENCE users_user_id_seq START WITH %s;', m);
  END IF;
END
$$;

-- 2) Make sequence owned by the column and set default
ALTER SEQUENCE users_user_id_seq OWNED BY users.user_id;
ALTER TABLE users ALTER COLUMN user_id SET DEFAULT nextval('users_user_id_seq');

-- 3) Assign new ids to any rows that have user_id = 0 (or NULL)
UPDATE users
SET user_id = nextval('users_user_id_seq')
WHERE user_id IS NULL OR user_id = 0;

-- 4) Verify there are no duplicates
-- This should return zero rows
SELECT user_id, COUNT(*) FROM users GROUP BY user_id HAVING COUNT(*) > 1;

-- 5) Optionally, if you want an identity column instead (Postgres >=10):
-- ALTER TABLE users ALTER COLUMN user_id DROP DEFAULT;
-- ALTER TABLE users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY;

-- End of script
